### ISSUE TITLE
Two-node cluster gets only two disks per storage node, regardless of number of storage nodes

### ISSUE THREAD

**Issue by smithfarm** [rjfd/sesdev#20]
The following command unexpectedly brings up a cluster with only two OSDs:

```
$ sesdev create nautilus --roles "[admin, storage, mon, mgr, mds], [client]" cephfuse 
=== Creating deployment with the following configuration ===
Deployment VMs:
  -- admin:
     - OS:               leap-15.1
     - ses_version:      nautilus
     - deployment_tool:  deepsea
     - roles:            ['admin', 'storage', 'mon', 'mgr', 'mds']
     - fqdn:             admin.cephfuse.com
     - public_address:   10.20.24.200
     - cpus:             2
     - ram:              4G
     - storage_disks:    2
       - /dev/vdb        8G
       - /dev/vdc        8G

  -- node1:
     - OS:               leap-15.1
     - ses_version:      nautilus
     - roles:            ['client']
     - fqdn:             node1.cephfuse.com
     - public_address:   10.20.24.201
     - cpus:             2
     - ram:              4G
     - custom_repos:
       - https://download.opensuse.org/repositories/filesystems:/ceph:/nautilus:/test
```

(See where it says `- storage_disks:    2`)

Since there is only one node with role `storage`, that node should get four disks.

**Comment by rjfd** [comment]
Actually it works with just 3 disks has in the `--single-node` configuration.

I think what we need to do is to change the logic that is implemented here: https://github.com/rjfd/sesdev/blob/master/sesdev/__init__.py#L230-L235

To instead of just checking if it's a single-node configuration, it should check how may storage nodes exist, and if there is only one, then deploy 3 disks on that node. And the new logic will also work for the single-node configuration.
